### ISSUE TITLE
Sveltekit "connect" is not exported by "__vite-browser-external"

### ISSUE THREAD

**Issue by WolfVector** [shanewholloway/js-u8-mqtt#11]
Hi, I'm trying to build a project using sveltekit. When I run `npm run build` using the node adapter, I get an error saying:

```js
"connect" is not exported by "__vite-browser-external", imported by "node_modules/u8-mqtt/esm/node/index.js".
file: D:/Documentos/svelte/black-dash/node_modules/u8-mqtt/esm/node/index.js:1:9

1: import { connect } from 'node:net';
            ^
2: import { connect as connect$1 } from 'node:tls';
[vite-plugin-sveltekit-compile] "connect" is not exported by "__vite-browser-external", imported by "node_modules/u8-mqtt/esm/node/index.js".
file: D:/Documentos/svelte/black-dash/node_modules/u8-mqtt/esm/node/index.js:1:9

1: import { connect } from 'node:net';
            ^
2: import { connect as connect$1 } from 'node:tls';
✓ built in 4.73s
error during build:
RollupError: "connect" is not exported by "__vite-browser-external", imported by "node_modules/u8-mqtt/esm/node/index.js".
    at error (file:///D:/Documentos/svelte/black-dash/node_modules/rollup/dist/es/shared/node-entry.js:2124:30)
    at Module.error (file:///D:/Documentos/svelte/black-dash/node_modules/rollup/dist/es/shared/node-entry.js:13463:16)
    at Module.traceVariable (file:///D:/Documentos/svelte/black-dash/node_modules/rollup/dist/es/shared/node-entry.js:13884:29)
    at ModuleScope.findVariable (file:///D:/Documentos/svelte/black-dash/node_modules/rollup/dist/es/shared/node-entry.js:12429:39)
    at ChildScope.findVariable (file:///D:/Documentos/svelte/black-dash/node_modules/rollup/dist/es/shared/node-entry.js:6965:38)
    at ClassBodyScope.findVariable (file:///D:/Documentos/svelte/black-dash/node_modules/rollup/dist/es/shared/node-entry.js:6965:38)
    at ChildScope.findVariable (file:///D:/Documentos/svelte/black-dash/node_modules/rollup/dist/es/shared/node-entry.js:6965:38)
    at FunctionScope.findVariable (file:///D:/Documentos/svelte/black-dash/node_modules/rollup/dist/es/shared/node-entry.js:6965:38)
    at ChildScope.findVariable (file:///D:/Documentos/svelte/black-dash/node_modules/rollup/dist/es/shared/node-entry.js:6965:38)
    at ReturnValueScope.findVariable (file:///D:/Documentos/svelte/black-dash/node_modules/rollup/dist/es/shared/node-entry.js:6965:38)
```

I'm following the sveltekit guide to generate the build. My `svelte.config.js` looks like this:
```js
import adapter from '@sveltejs/adapter-node';
import { vitePreprocess } from '@sveltejs/kit/vite';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	kit: {
		// adapter-auto only supports some environments, see https://kit.svelte.dev/docs/adapter-auto for a list.
		// If your environment is not supported or you settled on a specific environment, switch out the adapter.
		// See https://kit.svelte.dev/docs/adapters for more information about adapters.
		adapter: adapter()
	},
	preprocess: vitePreprocess()
};

export default config;
```

I'm pretty new to this whole world of frontend apps, so I don't know what I could be doing wrong. Maybe I should add some options to the adapter?

Thanks in advance.

**Comment by WolfVector** [comment]
I feel dumb. I just had to use `'u8-mqtt/esm/web/index.js'` instead of `'u8-mqtt'`

**Comment by shanewholloway** [comment]
No worries @WolfVector ! Glad you were able to find the solution! Welcome to the wild and wooly world of frontend development!

**Comment by mediafreakch** [comment]
I run into the same issue as well. It seems that Vite doesn't pickup the "browser" field in `package.json` automatically. It takes the "module" field instead. 

I stumbled upon a similar issue [here](https://github.com/vitejs/vite/issues/2329#issuecomment-789019270), so not sure if something can be done on `u8-mqtt` side to fix this?

**Comment by shanewholloway** [comment]
Thanks for the link — very helpful. I’m not familiar with using Sveltekit — would you mind creating a gist/repo that demonstrates the issue so I can be sure my fixes work?

**Comment by mediafreakch** [comment]
Since SvelteKit is using Vite as a bundler like Vue does, I created a reproduction repo using Vue, since I am more familiar with it. You can see it on Stackblitz: https://stackblitz.com/edit/vitejs-vite-ap4k83?file=src%2FApp.vue

Note the error in the terminal when building. Interestingly everything works as expected when running the app in development mode with `npm run dev`. You can try this by running this command in a separate terminal.

**Comment by shanewholloway** [comment]
Thanks for the excellent reproduction project. Used it to validate per-runtime package exports in `u8-mqtt@0.5.0`. Thanks for the feedback and re-raising this issue.

**Comment by mediafreakch** [comment]
Thank you, tested the 0.5.0 release and it works perfectly!
